wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.5
    start_time: 1656824771
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      4: 3.10.5
      5: 0.12.20
      8:
      - 1
      - 5
