wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1657144769
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      4: 3.8.10
      5: 0.12.21
      8:
      - 1
      - 5
decay:
  desc: null
  value: 0.006442809140465963
epochs:
  desc: null
  value: 700
learning_rate:
  desc: null
  value: 0.04192142124485789
model:
  desc: null
  value: Dias
