wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1657147343
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      4: 3.8.10
      5: 0.12.21
      8:
      - 1
      - 5
decay:
  desc: null
  value: 0.07642999083173016
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.07603127740653531
model:
  desc: null
  value: Dias
